#!/bin/bash

go build src/compile_.go src/config_.go src/decorations_.go src/main.go src/text_.go                                                                             
mv compile_ /usr/bin/cls

